title: GSoC org browser
page_gen:
  - data: orgs
    name: name
    template: org
    dir: orgs
page_gen-dirs: false
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - _data
jekyll_pages_api_search:
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
